gitlab-ci: Update test script to return explicit message when test failing + add build target

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -33,6 +33,18 @@ check-cleanarchi:
         -testPlatform $TEST_PLATFORM \
         -testResults $(pwd)/$TEST_PLATFORM-results.xml \
         -batchmode
+    UNITY_EXIT_CODE=$?
+    if [ $UNITY_EXIT_CODE -eq 0 ]; then
+      echo "Run succeeded, no failures occurred";
+    elif [ $UNITY_EXIT_CODE -eq 2 ]; then
+      echo "Run succeeded, some tests failed";
+    elif [ $UNITY_EXIT_CODE -eq 3 ]; then
+      echo "Run failure (other failure)";
+    else
+      echo "Unexpected exit code $UNITY_EXIT_CODE";
+    fi
+    exit $UNITY_TEST_EXIT_CODE
+
   artifacts:
     paths:
     - $(pwd)/$TEST_PLATFORM-results.xml
@@ -75,6 +87,17 @@ test-playmode:
     - ./Builds/
 #   only:
 #     - master
+
+build-StandaloneLinux64:
+  <<: *build
+  variables:
+    BUILD_TARGET: StandaloneLinux64
+
+build-StandaloneOSX:
+  image: registry.gitlab.com/teuteuf/unity3d:2018.2.6f1-mac
+  <<: *build
+  variables:
+    BUILD_TARGET: StandaloneOSX
 
 build-StandaloneWindows64:
   image: registry.gitlab.com/teuteuf/unity3d:2018.2.6f1-windows
